import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

/**
 * The linter exists for one class of bug: the kind the compiler cannot see.
 *
 * TypeScript already covers types, and Prettier owns formatting, so nothing
 * here argues about either — no stylistic rules, and no rules that would
 * disagree with `.prettierrc`. What is left is the rules of hooks, which is not
 * a type error and not a formatting question: `useCan()` placed below an early
 * return type-checks perfectly and breaks React at runtime, and that is exactly
 * how it reached the browser in Phase 8. The render matrix caught it from a
 * console error after the fact; this catches it at the keyboard.
 *
 * Type-aware linting is deliberately not switched on. It needs a TypeScript
 * program per run and turns a two-second check into a slow one, for rules that
 * mostly restate what `tsc --noEmit` already enforces in CI.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      'client/dist/**',
      'server/dist/**',
      // Generated by the shadcn CLI. Linting it only makes the next
      // `shadcn add` a noisy diff, which is the same reason Prettier skips it.
      'client/src/components/ui/**',
      'server/prisma/migrations/**',
      '**/*.tsbuildinfo',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx,js,mjs}'],
    rules: {
      /*
       * An unused argument is often deliberate — an Express error handler needs
       * all four parameters to be an error handler at all, and a caught error
       * that is intentionally swallowed reads better named than as a bare
       * `catch`. The underscore prefix is the signal.
       */
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
    },
  },

  {
    files: ['client/src/**/*.{ts,tsx}'],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      // The reason this config exists.
      'react-hooks/rules-of-hooks': 'error',
      // A warning rather than an error: the exhaustive list is frequently the
      // wrong answer for effects that deliberately run on one trigger, and
      // those cases are commented where they occur.
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  {
    files: ['server/**/*.ts', 'shared/**/*.ts', '*.js', '*.mjs', 'api/**/*.js'],
    languageOptions: { globals: globals.node },
  },
);
